export const PricingList=[
    {
        title:"Bronze Website Development",
        sub:"One Page Website",
        price:"15,999",
        list1:["One Page Website","Free Domain 1 Year*","Free Hosting 1 Year","Contact Form","Responsive Design","Professional Email Id 2"],
        list2:[],
    },
    {
        title:"Silver Website Development",
        sub:"Multi Page Website",
        price:"24,999",
        list1:["7 Pages Business Website", 
            "Customized Design",
            "Free Domain 1 Year*","Free Hosting 1 Year","SEO Ready Website", 
            "Business E-Mail 10", 
            "SSL Certificate ",
           " Control Panel" ],
        list2:["Responsive Design",
            "Customised Lead Form",
            "Content 1000 words", 
            "Social Media Integration", 
           "Google Analytics", 
            "Google Maps Integration", 
            "Customized Live Chat", 
            "Whatsapp Integration", 
            "High Speed Guarantee", 
            "Search Console Integration"],
    },
    {
        title:"Gold Website Development",
        sub:"E-Commerce Website",
        price:"49,999",
        list1:["E-Commerce Website", 
            "Customized Design",
            "Free Domain 1 Year*","Free Hosting 1 Year","SEO Ready Website", 
            "Business E-Mail 10", 
            "SSL Certificate ",
           " Control Panel" ],
        list2:["Responsive Design",
            "Content 1000 words", 
            "Social Media Integration", 
           "Google Analytics", 
            "Google Maps Integration", 
            "Advanced Live Chat Bot", 
            "Whatsapp Integration", 
            "High Speed Guarantee", 
            "Search Console Integration",
        "Payment Gateway Integrate"],
    },
    {
        title:"Bronze Website Development",
        sub:"One Page Website",
        price:"15,999",
        list1:["One Page Website","Free Domain 1 Year*","Free Hosting 1 Year","Contact Form","Responsive Design","Professional Email Id 2"],
        list2:[],
    },
    {
        title:"Silver Website Development",
        sub:"Multi Page Website",
        price:"24,999",
        list1:["7 Pages Business Website", 
            "Customized Design",
            "Free Domain 1 Year*","Free Hosting 1 Year","SEO Ready Website", 
            "Business E-Mail 10", 
            "SSL Certificate ",
           " Control Panel" ],
        list2:["Responsive Design",
            "Customised Lead Form",
            "Content 1000 words", 
            "Social Media Integration", 
           "Google Analytics", 
            "Google Maps Integration", 
            "Customized Live Chat", 
            "Whatsapp Integration", 
            "High Speed Guarantee", 
            "Search Console Integration"],
    },
    {
        title:"Gold Website Development",
        sub:"E-Commerce Website",
        price:"49,999",
        list1:["E-Commerce Website", 
            "Customized Design",
            "Free Domain 1 Year*","Free Hosting 1 Year","SEO Ready Website", 
            "Business E-Mail 10", 
            "SSL Certificate ",
           " Control Panel" ],
        list2:["Responsive Design",
            "Content 1000 words", 
            "Social Media Integration", 
           "Google Analytics", 
            "Google Maps Integration", 
            "Advanced Live Chat Bot", 
            "Whatsapp Integration", 
            "High Speed Guarantee", 
            "Search Console Integration",
        "Payment Gateway Integrate"],
    },
]